// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        (unknown)
// source: no_package/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TestProperty string `protobuf:"bytes,1,opt,name=testProperty,proto3" json:"testProperty,omitempty"`
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_no_package_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_no_package_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_no_package_message_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetTestProperty() string {
	if x != nil {
		return x.TestProperty
	}
	return ""
}

type HelloWorldMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloWorldMessage) Reset() {
	*x = HelloWorldMessage{}
	mi := &file_no_package_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloWorldMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorldMessage) ProtoMessage() {}

func (x *HelloWorldMessage) ProtoReflect() protoreflect.Message {
	mi := &file_no_package_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorldMessage.ProtoReflect.Descriptor instead.
func (*HelloWorldMessage) Descriptor() ([]byte, []int) {
	return file_no_package_message_proto_rawDescGZIP(), []int{1}
}

func (x *HelloWorldMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_no_package_message_proto protoreflect.FileDescriptor

var file_no_package_message_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6e, 0x6f, 0x5f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x0b, 0x54, 0x65,
	0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x65, 0x73,
	0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x74, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x22, 0x2d, 0x0a,
	0x11, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x3c, 0x5a, 0x3a,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x72, 0x70, 0x6f, 0x74,
	0x61, 0x74, 0x6f, 0x73, 0x73, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65,
	0x6e, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_no_package_message_proto_rawDescOnce sync.Once
	file_no_package_message_proto_rawDescData = file_no_package_message_proto_rawDesc
)

func file_no_package_message_proto_rawDescGZIP() []byte {
	file_no_package_message_proto_rawDescOnce.Do(func() {
		file_no_package_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_no_package_message_proto_rawDescData)
	})
	return file_no_package_message_proto_rawDescData
}

var file_no_package_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_no_package_message_proto_goTypes = []any{
	(*TestMessage)(nil),       // 0: TestMessage
	(*HelloWorldMessage)(nil), // 1: HelloWorldMessage
}
var file_no_package_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_no_package_message_proto_init() }
func file_no_package_message_proto_init() {
	if File_no_package_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_no_package_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_no_package_message_proto_goTypes,
		DependencyIndexes: file_no_package_message_proto_depIdxs,
		MessageInfos:      file_no_package_message_proto_msgTypes,
	}.Build()
	File_no_package_message_proto = out.File
	file_no_package_message_proto_rawDesc = nil
	file_no_package_message_proto_goTypes = nil
	file_no_package_message_proto_depIdxs = nil
}
